Allow escaping quotations in quoted macro arguments.
gollum/gollum-lib pull request #406
Opened 2021-12-09 17:51 UTC by srbaker

This allows using quotation marks inside quoted macro arguments.

Example:

```
<<MyMacro("This is only \"one\" quoted argument.")>>
```

2021-12-09 18:01 UTC, dometto requested changes
Thanks for the contribution! Surprised this works with so little changes, neatly done.

Does this relate to an existing issue in https://github.com/gollum/gollum? If so please link it.

2021-12-09 18:15 UTC, dometto commented
The test failures on JRuby are due to the issue described in https://github.com/gollum/gollum/issues/1779. Downgrading to `nokogiri v. 1.12.4` locally makes the JRuby tests pass.

2021-12-09 18:31 UTC, srbaker commented on lib/gollum-lib/filter/macro.rb
> +          args << Regexp.last_match[1].gsub("\\\"", "\"")
Sorry about that.  Fixed.

2021-12-09 18:31 UTC, srbaker commented on lib/gollum-lib/filter/macro.rb
> +    quoted_arg   = %r{".*?(?<!\\)"}
Done!

2021-12-09 18:32 UTC, srbaker commented
There is no issue.  I noticed this after fighting with a new macro on a new wiki last night, and was very confused. :D

I didn't know _how_ to do the negative lookbehind until I looked it up, I just knew it was possible. :D

2022-01-22 00:06 UTC, srbaker commented
Heya, sorry to bother.  Want to bump this.  I think everything is addressed and it should be ready to go.

Thanks!

2022-01-22 10:21 UTC, dometto approved these changes

2022-01-22 10:24 UTC, dometto commented
Sorry I missed this! The CI tests for this PR are somehow not running. Gonna see if they get triggered if I close and reopen this PR.

2022-01-22 10:29 UTC, dometto commented
Green lights! Thanks again @srbaker

2022-01-22 10:29 UTC, merged

2022-01-31 22:24 UTC, srbaker commented
Thanks so much!